name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Deploy to Server
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
        chmod 600 ssh_key

        ssh -o StrictHostKeyChecking=no -i ssh_key ${{ secrets.PROD_USER }}@api.search.zawie.io "cd ~/zearch-engine && sudo ./forcerun.sh"
